---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[ocsinventory-agent::default]
